version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:3000
      - --api.insecure=true
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.replacePathHealth.replacepath.path=/health
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - internal

  user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      - REDIS_URI=redis://redis:6379
      - USER_SERVICE_PORT=5000
    command: [user-service]
    labels:
      - traefik.enable=true
      - traefik.http.services.user-service.loadbalancer.server.port=5000
      - traefik.http.routers.userHomeRouter.rule=Host(`localhost`) && Path(`/`)
      - traefik.http.routers.userRegisterRouter.rule=Host(`localhost`) && Path(`/register`)
      - traefik.http.routers.userMatchRouter.rule=Host(`localhost`) && Path(`/match`)
      - traefik.http.routers.userHealthRouter.rule=Host(`localhost`) && PathPrefix(`/user/health`)
      - traefik.http.routers.userHealthRouter.middlewares=replacePathHealth
    networks:
      - internal

  chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-service
    environment:
      - REDIS_URI=redis://redis:6379
      - CHAT_SERVICE_PORT=5001
    command: [chat-service]
    labels:
      - traefik.enable=true
      - traefik.http.services.chat-service.loadbalancer.server.port=5001
      - traefik.http.routers.chatWSRouter.rule=Host(`localhost`) && PathPrefix(`/chat/`)
      - traefik.http.routers.chatHealthRouter.rule=Host(`localhost`) && PathPrefix(`/chat/health`)
      - traefik.http.routers.chatHealthRouter.middlewares=replacePathHealth
    networks:
      - internal

  forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forwarder-service
    environment:
      - REDIS_URI=redis://redis:6379
    command: [forwarder-service]
    labels:
      - traefik.enable=false
    networks:
      - internal

networks:
  internal:
    driver: bridge